### PR TITLE
Incorporate certain object dynamics

### LINKED ISSUE #1782: Implement objects sticking to solids
In the recent improvements to moving objects, the movement from the moving object is applied to those who stand on it. It would be interesting to add a similar thing but for the sides and bottom of the moving object.  This would only apply to objects with a set "sticky" attribute, and would simulate sticking objects to things.
  This could apply to dart traps, bumpers, levers, the upcoming crystal shards, and other objects who currently do not stick to the sides of solids and instead simply stand by themselves, which produces unexpected behavior.

### LINKED ISSUE #2909: Small Tux can't unhold rock if he is pushed against ceiling
On current nightly, if you are small Tux and are for some reason pressed up against a ceiling, you can't unhold the rock.  This is bad because if a rock's grab script is set to send Tux up somehow, then he can never get back down.

### LINKED ISSUE #2912: Rock doesn't die when falling out of sector
If a rock falls out of a sector it just falls forever when it should probably just disappear.

### PR DESCRIPTION
**Pull request by weluvgoatz**
For my 100th PR, I decided to fix some old issues I had involving the dynamics between some objects.  Included in this PR are the following:
- Rocks no longer hurt Tux and bounce off of him, making rock puzzles more fair.
- Rocks now interact as expected with slick ice, water, bumpers, and trampolines.
- Enemies now interact as expected with water, bumpers, and trampolines. 
- Objects oriented to the side (switches, darttraps, bumpers, stalactites, yeti stalactites, pushbuttons, ispys, and shards) now properly stick to moving objects which look like they can be stuck to (moving tilemaps, platforms, crushers and fallblocks). [Fixes #1782]

Note: I was hoping to incorporate some more general method for point 4, where I didn't have to specify every single interaction and I could just label some objects as "sticky" and "sticked" objects, but this proved to be difficult as I don't think the game is currently capable of describing objects in such a way that I could do that, and I did not want to spend this PR refactoring some part of the game just to include that little thing.  Each of the different possible interactions tends to have to some slight variation from one another, and there aren't very many of these possible interactions, anyway.  

Fixes #2909 Fixes #2912

### CODE REVIEW

**Comment by Narre** [comment]
Not sure about the consistency of this behaviour. Also, the objects should probably only move with the tilemap/fallblock/... that's behind them to avoid situations like on the right side in the first video.

https://github.com/SuperTux/supertux/assets/14074789/420b416c-db53-4bac-9bea-fbb60cd80923

Also, this completely breaks this level (there are many more switches like this in it) and pretty much any level that has a lift controlled by a switch.

https://github.com/SuperTux/supertux/assets/14074789/986416ee-aead-4510-a5b2-d016a8c17690

**Comment by bruhmoent** [comment]
Maybe objects should have the ability to be immovable

**Comment by VincentAraneo** [comment]
In my personal opinion, this idea is great. It would serve a lot in puzzle levels. An idea like that wouldn't be bad, you could make more creative levels with that idea

**Comment by tylerandari13** [comment]
> Also, this completely breaks this level (there are many more switches like this in it) and pretty much any level that has a lift controlled by a switch.

Not gonna lie this looks sick. I understand its technically broken but this would be a really cool thing to play around with.

> Maybe objects should have the ability to be immovable

I agree, like an "immobile" option on the objects.

**Review by Frostwithasideofsalt — APPROVED** [review]

**Comment by tobbi** [comment]
That is a lot of code duplication. Can this be done in other ways so we only have the same code once?

**Comment by weluvgoatz** [comment]
> That is a lot of code duplication. Can this be done in other ways so we only have the same code once?

I tried to find ways around it, but it appears the way each object is handled is done differently in such a way that at least I couldn't personally get it to work.

**Comment by tobbi** [comment]
How about moving this to a parent GameObject method?

**Comment by tylerandari13** [comment]
Are stalactites/yeti stalactites also sticky objects? And if not can they be?

**Comment by weluvgoatz** [comment]
> How about moving this to a parent ~GameObject~ BadGuy class method?

Now I am probably going to refactor the PR with this is mind.

File: src/object/sticky_object.cpp [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+
+#include "object/sticky_object.hpp"
+
+#include "badguy/badguy.hpp"
+#include "object/fallblock.hpp"
+#include "object/moving_sprite.hpp"
+#include "object/platform.hpp"
+#include "object/tilemap.hpp"
+#include "supertux/sector.hpp"
+#include "util/reader_mapping.hpp"
```
Comment (Vankata453) [inline src/object/sticky_object.cpp:25]: Unneeded include.

File: src/object/sticky_object.hpp [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+//
+//  You should have received a copy of the GNU General Public License
+//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+#ifndef HEADER_SUPERTUX_OBJECT_STICKY_OBJECT_HPP
+#define HEADER_SUPERTUX_OBJECT_STICKY_OBJECT_HPP
+
+#include "badguy/badguy.hpp"
+#include "object/moving_sprite.hpp"
+#include "supertux/game_object.hpp"
```
Comment (Vankata453) [inline src/object/sticky_object.hpp:22]: No need to include `GameObject`.

File: src/object/shard.cpp [hunk 3]
```diff
@@ -19,12 +19,16 @@
 #include "audio/sound_manager.hpp"
 #include "badguy/badguy.hpp"
 #include "math/util.hpp"
+#include "object/fallblock.hpp"
 #include "object/player.hpp"
+#include "object/platform.hpp"
+#include "object/tilemap.hpp"
 #include "sprite/sprite.hpp"
+#include "supertux/sector.hpp"
```
Comment (Vankata453) [inline src/object/shard.cpp:27]: Unneeded includes.

**Review by Vankata453 — CHANGES_REQUESTED** [review]
Functionality-wise, this seems to work really well!

Left some code-related comments.

File: src/object/sticky_object.hpp [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+  bool m_sticky; // determines if the object CAN stick, period. 
+  bool m_sticking; // determines if the object has found something to stick to.
+  //GameObject* m_owner = nullptr;
+
+private:
+  StickyObject(const StickyObject&) = delete;
+  StickyObject& operator=(const StickyObject&) = delete;
+};
+
+class StickyBadguy : public BadGuy
```
[the remark this answers is not in the document]
Comment (weluvgoatz) [reply src/object/sticky_object.hpp:50]: I named it that way to keep it consistent with the `WalkingBadguy` class.

**Review by Vankata453 — APPROVED** [review]

**Review by MatusGuy — CHANGES_REQUESTED** [review]
Interesting, Dart traps don't shoot if too close to a platform, but if you put them a little bit far apart they do.

https://github.com/SuperTux/supertux/assets/85036874/9f3f9034-d9e7-4314-9880-7eef99ad55f4

File: src/badguy/darttrap.cpp [hunk 5]
```diff
@@ -147,11 +154,12 @@ DartTrap::get_settings()
 
   result.add_float(_("Initial delay"), &m_initial_delay, "initial-delay");
   result.add_bool(_("Enabled"), &m_enabled, "enabled", true);
+  result.add_bool(_("Sticky"), &m_sticky, "sticky", false);
```
[the remark this answers is not in the document]
Comment (Vankata453) [reply src/badguy/darttrap.cpp:157]: I thought the same, but turns out that for some objects it should be configurable, but for others - not.

[the remark this answers is not in the document]
Comment (Vankata453) [reply src/badguy/darttrap.cpp:157]: Yeah, that's also a way.

**Review by MatusGuy — APPROVED** [review]

**Review by Rusty-Box — COMMENTED** [review]
There seems to be quite a few things off, not gonna lie.

1. Sticky objects lag (lack for a better term) behind the actual moving platform ever so slightly. Very rough for Dart Trap who on occasion is blocked from firing that way! They also get very easily pushed around by other sticky objects (or maybe it's the moving platforms, can't quite tell)

https://github.com/SuperTux/supertux/assets/20615048/f362e884-c8ef-4333-bfd7-79541c84f75f

2. The affect on objects by water is very weak. Horizontal speed for badguys remains the same and gravity is barely changed. Both should be affected much stronger.
3. Throwing objects as well as Jumpy jumping is waaay more stronger underwater which doesn't make much sense. Both should only fall slower, not accelerate underwater.
4. I like seeing submerged Ivy floating towards the top but once there, they move very weirdly. A very awkward up and down motion. It's even worse than that of the Fish. I know this is to give a sense of water waves affecting them but this needs to be way more subtle. Also when they reach the water surface they submerge again for a bit before coming up top again. Very weird looking. Once they reach the top of the water, they should remain there

**Review by Rusty-Box — COMMENTED** [review]
Okay, this is much, much better now. The delay of sticky objects is fixed, floating ivy's feel much better now as well as water physics for badguys.

A couple more requests regarding water physics:
- Projectiles, like fire and ice bullets should be much slower too. Imo they are way to fast making them feel rather spastic and weird
- I might be seeing things, but I feel that some underwater enemies, like Dive Mine and Fish are also affectd speed-wise by water? Not sure, could just be my eye playing tricks on me

There might be a few minor things I can't recall right now but these are my only requests for now. Otherwise this look better now.

**Comment by Sevenberry** [comment]
trappedforeternity
Feel we should allow tux to pick up items whilst crawling, ended up getting myself trapped whilst testing a level

**Review by Rusty-Box — APPROVED** [review]

**Comment by weluvgoatz** [comment]
> trappedforeternity Feel we should allow tux to pick up items whilst crawling, ended up getting myself trapped whilst testing a level

I'd consider this more relevant to another PR.  I think this PR has all the additions I'm willing to make in it for now. You can make an issue for it you want so I can keep track of it, or I can make the issue myself.

File: src/object/bumper.cpp [hunk 6]
```diff
@@ -75,6 +105,16 @@ Bumper::collision(GameObject& other, const CollisionHit& hit)
     SoundManager::current()->play(TRAMPOLINE_SOUND, get_pos());
     set_action("swinging", m_dir, 1);
   }
+
+  auto badguy = dynamic_cast<BadGuy*> (&other);
+  if (badguy)
+  {
+    float BOUNCE_DIR = (m_dir == Direction::LEFT) ? -400.f : 400.f;
+    badguy->get_physic().set_velocity(BOUNCE_DIR, 0.f);
```
Comment (Vankata453) [inline src/object/bumper.cpp:113]: No need for a variable here.

File: src/object/fallblock.hpp [hunk 7]
```diff
@@ -43,7 +43,10 @@ class FallBlock : public MovingSprite
 
   virtual void on_flip(float height) override;
 
-protected:
+public:
+
```
Comment (Vankata453) [inline src/object/fallblock.hpp:47]: Get rid of this space.

File: src/object/bumper.cpp [hunk 8]
```diff
@@ -60,7 +64,33 @@ Bumper::update(float dt_sec)
...
+  Rectf small_overlap_box = get_bbox().grown(1.f);
+
+  for (auto& rock : Sector::get().get_objects_by_type<Rock>())
+  {
+    if (small_overlap_box.overlaps(rock.get_bbox()))
+    {
+      float BOUNCE_DIR = m_dir == Direction::LEFT ? -BOUNCE_X : BOUNCE_X;
+      rock.get_physic().set_velocity(BOUNCE_DIR * 0.7f, BOUNCE_Y * 0.6f);
+      SoundManager::current()->play(TRAMPOLINE_SOUND, get_pos());
+      m_sprite->set_action("swinging", m_dir, 1);
```
Comment (Vankata453) [inline src/object/bumper.cpp:79]: Call this directly on `this` for a collision-safe approach (applies to `MovingSprite`s):

```suggestion
      set_action("swinging", m_dir, 1);
```

**Review by Vankata453 — COMMENTED** [review]
Additionally, I *might* have an idea on how to fix code duplication in "sticky_object.cpp" so I will try that out.

**Review by Vankata453 — APPROVED** [review]

File: src/badguy/badguy.cpp [hunk 9]
```diff
@@ -181,6 +183,15 @@ BadGuy::update(float dt_sec)
...
   {
+    Rectf playerbox = get_bbox().grown(-2.f);
+    playerbox.set_bottom(get_bbox().get_bottom() + 7.f);
+    for (auto& player : Sector::get().get_objects_by_type<Player>())
+    {
+      if (playerbox.overlaps(player.get_bbox()) && m_physic.get_velocity_y() > 0.f && is_portable()) {
+        m_physic.set_velocity_y(-250.f);
+      }
+    }
+
```
Comment (MatusGuy) [inline src/badguy/badguy.cpp:194]: What does this do?

File: src/badguy/badguy.cpp [hunk 10]
```diff
@@ -325,7 +382,10 @@ void
 BadGuy::active_update(float dt_sec)
 {
   if (!is_grabbed())
-    m_col.set_movement(m_physic.get_movement(dt_sec));
+    m_col.set_movement(m_physic.get_movement(dt_sec) * (m_water_affected ? (
+      Vector((is_in_water() && !m_frozen) ? 0.7f : (is_in_water() && m_frozen) ? 0.1f : 1.f,
+             (is_in_water() && !m_frozen) ? 0.3f : (is_in_water() && m_frozen) ? 0.6f : 1.f)) :
+      Vector(1.f, 1.f)));
```
Comment (MatusGuy) [inline src/badguy/badguy.cpp:388]: Please split these ternary operators into separate if statements.

**Review by MatusGuy — APPROVED** [review]

**Comment by MatusGuy** [comment]
I didn't mean to approve this. I meant to only comment on it without explicit approval

File: src/badguy/badguy.cpp (hunk 9 above)
Comment (weluvgoatz) [reply src/badguy/badguy.cpp:194]: Makes the frozen enemies bounce off Tux's head like rocks.

File: src/badguy/badguy.cpp (hunk 10 above)
Comment (weluvgoatz) [reply src/badguy/badguy.cpp:388]: Why

Comment (MatusGuy) [reply src/badguy/badguy.cpp:388]: Nested ternary operators are generally pretty unpleasant to read. They jam everything into a single line instead of going step by step. Ternary operators should only be used for simple cases.

Comment (tylerandari13) [reply src/badguy/badguy.cpp:388]: I saw this on the GitHub channel on Discord and thought "this cant be *that* bad".

It is that bad.

I cant read this lol.

Comment (weluvgoatz) [reply src/badguy/badguy.cpp:388]: Alright, I can fix it
