### PR TITLE
Fix smart BadGuy movement on e.g. rocks

### LINKED ISSUE #2194: Plants and totems do not behave properly when placed on rocks that are atop of trampolines
SuperTux version:| 0.6.3

Expected behavior:| Totems and plants should be able to walk on rocks like other enemies can.

Actual behavior:| The plant in the video below appears to clip into the rocks after the falling rocks and comes back out, and it seems to be in its moving animation/position even though it itself isn't moving. The totem touches the rock(s) and doesn't move around; instead it acts glitchy by repeating its left and right walking animations constantly / consistently.

Steps to reproduce actual behavior:|
Video below

Additional debugging information:|

https://user-images.githubusercontent.com/83178674/164649289-54f11452-b9b8-4497-b9ab-a24e6ae18023.mp4

### PR DESCRIPTION
**Pull request by AidenIsik**
This fixes a bug where "smart" badguys can't move when walking on rocks.

I just modified the BadGuy::might_fall() function to also check for "movablestatics" in the return, which makes the smart
badguys no longer act like they are about to walk off of an edge when they're really just walking on rocks (maybe this also fixes other things badguys can walk on too).

Closes #2194

### CODE REVIEW

**Comment by AidenIsik** [comment]
This seems to allow smart badguys to walk on tux and enemies if they are one tile down and next to the level where they are walking. I need to revise this slightly.

**Review by tobbi — APPROVED** [review]
Seems easy enough to just outright approve.

**Comment by MatusGuy** [comment]
Shouldn't we wait for someone to test this?

**Comment by tobbi** [comment]
Just from the code logic, this seems reasonable, but fine...

**Comment by tobbi** [comment]
Testing my ass

**Comment by AidenIsik** [comment]
Please don't merge yet I need to change it a bit later:

is_free_of_movingstatics includes COLGROUP_MOVING. I need to make a slightly modified version of that function excluding COLGROUP_MOVING and use that instead.

**Comment by Rusty-Box** [comment]
> Testing my ass

That's not how this works.

**Comment by tobbi** [comment]
> Please don't merge yet I need to change it a bit later:
> 
> is_free_of_movingstatics includes COLGROUP_MOVING. I need to make a slightly modified version of that function excluding COLGROUP_MOVING and use that instead (perhaps calling it is_free_of_only_movingstatics)

I've marked it as a draft for you.

**Comment by AidenIsik** [comment]
Thanks. I'll get this done in a few hours.

**Comment by MatusGuy** [comment]
Tobbi I've seen stuff break because a little insignificant thing was merged. Just don't be like that

**Comment by MatusGuy** [comment]
> Just from the code logic, this seems reasonable, but fine...

If it was an or (`||`) it'd be fine but you better be careful with the ands

**Comment by tobbi** [comment]
Yeah okay that went over my head

**Comment by tobbi** [comment]
> > Just from the code logic, this seems reasonable, but fine...
> 
> If it was an or (`||`) it'd be fine but you better be careful with the ands

&& is just fine. That function shold return true when both conditions are.

**Comment by AidenIsik** [comment]
Done.

**Review by tobbi — APPROVED** [review]

**Comment by MatusGuy** [comment]
Yo tobbi did you actually test this time?

File: src/collision/collision_system.cpp [hunk 1]
```diff
@@ -714,6 +714,22 @@ CollisionSystem::is_free_of_movingstatics(const Rectf& rect, const CollisionObje
...
+bool
+CollisionSystem::is_free_of_specifically_movingstatics(const Rectf& rect, const CollisionObject* ignore_object) const
+{
+  using namespace collision;
+
+  for (const auto& object : m_objects) {
+    if (object == ignore_object) continue;
+    if (!object->is_valid()) continue;
+    if ((object->get_group() == COLGROUP_MOVING_STATIC)) {
+      if (intersects(rect, object->get_bbox())) return false;
```
Comment (mrkubax10) [inline src/collision/collision_system.cpp:726]: These could be merged to single `if`.

Comment (AidenIsik) [reply src/collision/collision_system.cpp:726]: Do you want me to do that for the other functions with redundant if statements, or just this new one?

Comment (mrkubax10) [reply src/collision/collision_system.cpp:726]: Only these that you added, changing all of them would be out of this PR scope.

File: src/badguy/badguy.cpp [hunk 2]
```diff
@@ -775,7 +775,7 @@ BadGuy::might_fall(int height) const
     x1 = m_col.m_bbox.get_right();
     x2 = m_col.m_bbox.get_right() + 1;
   }
-  return Sector::get().is_free_of_statics(Rectf(x1, y1, x2, y2));
+  return Sector::get().is_free_of_statics(Rectf(x1, y1, x2, y2)) && Sector::get().is_free_of_specifically_movingstatics(Rectf(x1, y1, x2, y2));
```
Comment (Vankata453) [inline src/badguy/badguy.cpp:778]: The `Rectf(x1, y1, x2, y2)` rectangle could be created in a `const Rectf` variable above and then copied, saving another initialization.

**Review by mrkubax10 — APPROVED** [review]

**Comment by tobbi** [comment]
Thank you for your contribution!
