### PR TITLE
Multiplayer

### LINKED ISSUE #224: Local 2+ Player Multiplayer
A few steps to this:
- [ ] Format
  -  Split Screen
  -  [One Screen](https://youtu.be/pipMu0HXiU0?t=50s)
- [ ] Second player (with sprites)
  - Penny?
- [ ] New control configs for new player
- [ ] Play campaign?

### LINKED ISSUE #852: Multiplayer: Save player controls for multiple players in settings file
Currently, only the player controls for one player are saved in the ```keymap``` property in the settings file. If we want to support multiple players, we need to save player controls for both players in the settings.

**If we do this, we still need a backwards compatible way of reading the previous keymap settings, so that those don't get lost.** 

This will need a bit of discussion, I guess. So I'm gonna mark it as such.

### LINKED ISSUE #1537: Current Action key (Alt) conflicts with system shortcuts
**SuperTux version:** 0.6.2
**System information:** *Ubuntu 20.04*

Hello, I have found that the default Action key for me (Alt) conflicts with some system shortcuts (Example: Alt+Space opens the window menu), so I'd suggest changing it, I know changing keyboard controls exist, but again, I'd suggest that you change the default Action key.

Note: Sorry for the kinda bad English here, English is not my first language.

### LINKED ISSUE #2057: Star powerup music doesn't pause on level pause
**SuperTux version:** 0.6.3
**System information:** Windows 10

##### Expected behavior
When a player gets the star powerup and pauses the level, the powerup's music pauses too.
##### Actual behavior
When a player gets the star powerup and pauses the level, the powerup's music continues to play, which also makes it out of sync when playing the level.
##### Steps to reproduce actual behavior
Get the star powerup in a level, then pause. Unpause a few seconds after.
***
Another issue is that the beginning sound, before the star powerup's music plays, stops playing altogether, when the level is paused.

### PR DESCRIPTION
**Pull request by Semphriss**
'Nuff said.

Fixes #224
Fixes #852
Closes #1956

Additionally:
Fixes #2057
Fixes #1537 

Supports:
- Any number of player
- Control both joysticks/controllers and keyboard for all players
- Hot-plugging of controllers automatically spawn/de-spawn players if there is an active sector that isn't the title screen
- Manual configuration through the options menu
- Stats saved for all players, persistent even if a certain player doesn't play for a long time
- Adaptive camera to track all players on screen

https://user-images.githubusercontent.com/66701383/147707597-044a5718-3bab-4083-82f9-011c35f0cd58.mp4

(Sorry for the non-simultaneous movements, it's hard to play two players with two hands)

### Split screen?

Split screen has been considered and will likely be added in the future, but it requires some improvements to the rendering engine first so it supports cropping properly. I've already done that for another unreleased PR, so I know it's possible and I know how to do it, but I need to actually take the time to do it, so it won't be immediate.

### CODE REVIEW

**Comment by Semphriss** [comment]
**NOTE:** I intend to clean up the code a lot; I opened the PR only to call for testers to help me find bugs in the PR. I don't mind reviews, but most of this code *will* change, and I will review myself and correct or change some stuff.

File: src/object/bonus_block.cpp [hunk 1]
```diff
@@ -266,7 +266,7 @@ BonusBlock::try_open(Player* player)
     return;
 
   if (player == nullptr)
-    player = &Sector::get().get_player();
+    player = Sector::get().get_nearest_player(m_col.m_bbox);
```
Comment (Zwatotem) [inline src/object/bonus_block.cpp:269]: `get_nearest_player` is bound to cause some strange interactions in some cases, but it's good enough for now, I guess.

Comment (Semphriss) [reply src/object/bonus_block.cpp:269]: It picks the nearest player if and only if there is no player that performed the `try_open` (such as an iceblock or a portable, if I look at the source code).

Perhaps an idea would be to make iceblocks/portables open bonus blocks from the perspective of the player who threw the object? But would require having them keep track of which player(s) interact with them, and it wouldn't take into account the cases where they hit a bonus block without any player interaction.

**Comment by serano01** [comment]
I'm not sure about "any number of players". Two players would be sufficient, more would lead to pure chaos. Most levels are still designed for one player in mind. This way the second player can be an all new character instead of a oddly colored Tux.

**Comment by Semphriss** [comment]
> I'm not sure about "any number of players". Two players would be sufficient, more would lead to pure chaos. Most levels are still designed for one player in mind. This way the second player can be an all new character instead of a oddly colored Tux.

Better not to hardcode the player restriction :^) Plus, the pure chaos is sometimes part of the fun at parties. (Am I the only one who always plays STK with the maximum number of AIs?)

The colors are meant to be temporary; there has been some discussion with various people about making a bunch of playable characters, although there isn't any centralized place to hold all that yet.

File: src/control/joystick_manager.hpp [hunk 2]
```diff
@@ -40,13 +47,15 @@ class JoystickManager final
...
 
-  void set_joy_controls(Control id, bool value);
+  void set_joy_controls(SDL_JoystickID joystick, Control id, bool value);
 
   void on_joystick_added(int joystick_index);
   void on_joystick_removed(int instance_id);
 
   int get_num_joysticks() const { return static_cast<int>(joysticks.size()); }
 
+  std::unordered_map<SDL_Joystick*, int>& get_joystick_mapping() { return joysticks; }
```
Comment (tobbi) [inline src/control/joystick_manager.hpp:57]: Can this actually be marked const as well?

File: src/object/player.cpp [hunk 3]
```diff
@@ -129,14 +130,24 @@ const float SMALL_TUX_HEIGHT = 30.8f;
...
 } // namespace
 
-Player::Player(PlayerStatus& player_status, const std::string& name_) :
+Color
+Player::get_player_color(int id)
+{
+  return Color(1.f - static_cast<float>(id >> 2 & 1) * .4f,
+               1.f - static_cast<float>(id >> 1 & 1) * .4f,
+               1.f - static_cast<float>(id & 1) * .4f);
+}
```
Comment (tobbi) [inline src/object/player.cpp:141]: I believe this can be marked const.

File: src/supertux/game_session.cpp [hunk 4]
```diff
@@ -67,31 +66,46 @@ GameSession::GameSession(const std::string& levelfile_, Savegame& savegame, Stat
...
 {
-  m_currentsector->get_player().set_bonus(m_bonus_at_start);
+  for (const auto& p : m_currentsector->get_players())
+  {
+    try
+    {
+      p->set_bonus(m_boni_at_start.at(p->get_id()));
+    }
+    catch(const std::out_of_range&)
+    {
```
Comment (tobbi) [inline src/supertux/game_session.cpp:102]: Can this actually happen? You're resizing the array to the number of users in the constructor.

File: src/supertux/menu/cheat_apply_menu.cpp [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+  m_callback_2(nullptr),
+  m_stack_count(-1)
+{
+  add_label(_("Apply cheat to player"));
+  add_hl();
+
+  add_entry(-1, _("All Players"));
+  for (const auto player : Sector::get().get_players())
+  {
+    add_entry(player->get_id(), _("Player") + " " +
```
Comment (tobbi) [inline src/supertux/menu/cheat_apply_menu.cpp:37]: Can you use some kind of string::format call? One that our translation functions can understand?

File: src/supertux/menu/cheat_apply_menu.cpp [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+{
+  add_label(_("Apply cheat to player"));
+  add_hl();
+
+  add_intfield("Count", &m_stack_count, -2);
+  add_hl();
+  add_entry(-1, _("All Players"));
+  for (const auto player : Sector::get().get_players())
+  {
+    add_entry(player->get_id(), _("Player") + " " +
```
Comment (tobbi) [inline src/supertux/menu/cheat_apply_menu.cpp:58]: see above

File: src/supertux/menu/multiplayer_players_menu.cpp [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+#include "util/gettext.hpp"
+
+MultiplayerPlayersMenu::MultiplayerPlayersMenu()
+{
+  add_label(_("Multiplayer"));
+  add_hl();
+
+  for (int i = 0; i < InputManager::current()->get_num_users(); i++)
+  {
+    add_entry(_("Player") + " " + std::to_string(i + 1), [i] {
```
Comment (tobbi) [inline src/supertux/menu/multiplayer_players_menu.cpp:35]: String l10n functions

File: src/supertux/menu/worldmap_cheat_apply_menu.cpp [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+  m_num_players(num_players),
+  m_callback_1(callback),
+  m_callback_2(nullptr),
+  m_stack_count(-1)
+{
+  add_label(_("Apply cheat to player"));
+  add_hl();
+
+  for (int i = 0; i < m_num_players; i++)
+    add_entry(i, _("Player") + " " + std::to_string(i + 1));
```
Comment (tobbi) [inline src/supertux/menu/worldmap_cheat_apply_menu.cpp:37]: string l10n functions

File: src/supertux/menu/worldmap_cheat_apply_menu.cpp [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+{
+  add_label(_("Apply cheat to player"));
+  add_hl();
+
+  add_intfield("Count", &m_stack_count, -2);
+  add_hl();
+  add_entry(-1, _("All Players"));
+
+  for (int i = 0; i < m_num_players; i++)
+    add_entry(i, _("Player") + " " + std::to_string(i + 1));
```
Comment (tobbi) [inline src/supertux/menu/worldmap_cheat_apply_menu.cpp:58]: string l10n functions

File: src/supertux/menu/worldmap_cheat_menu.cpp [hunk 10]
```diff
@@ -67,33 +68,48 @@ WorldmapCheatMenu::menu_action(MenuItem& item)
...
-      status.bonus = EARTH_BONUS;
+      do_cheat(status, [&status](int player, int count){
+        status.bonus[player] = EARTH_BONUS;
+        status.max_earth_time[player] = count;
+      });
       break;
 
     case MNID_SHRINK:
-      status.bonus = NO_BONUS;
+      do_cheat(status, [&status](int player){
```
Comment (tobbi) [inline src/supertux/menu/worldmap_cheat_menu.cpp:105]: formatting for all of those: missing space before `{`

File: src/supertux/sector.cpp [hunk 11]
```diff
@@ -394,9 +413,62 @@ Sector::draw(DrawingContext& context)
 {
   BIND_SECTOR(*this);
 
-  Camera& camera = get_camera();
+#if 0
+  context.push_transform();
```
Comment (tobbi) [inline src/supertux/sector.cpp:417]: What is this region for?

File: src/supertux/sector.cpp [hunk 12]
```diff
@@ -713,10 +786,21 @@ Sector::get_camera() const
...
+std::vector<Player*>
+Sector::get_players() const
 {
-  return *static_cast<Player*>(get_objects_by_type_index(typeid(Player)).at(0));
+  auto players_raw = get_objects_by_type<Player>();
+
+  std::vector<Player*> players;
+
+  auto it = players_raw.begin();
+  while (it != players_raw.end())
```
Comment (tobbi) [inline src/supertux/sector.cpp:797]: Can you not use `std::transform` for this?

File: src/trigger/climbable.cpp [hunk 13]
```diff
@@ -136,9 +133,17 @@ Climbable::event(Player& player, EventType type)
       }
     }
   }
+
   if (type == EVENT_LOSETOUCH) {
     player.stop_climbing(*this);
-    climbed_by = nullptr;
+    auto it = climbed_by.begin();
```
Comment (tobbi) [inline src/trigger/climbable.cpp:139]: We don't use c++20 yet, do we? Otherwise, you could've used std::erase_if

File: src/video/canvas.cpp [hunk 14]
```diff
@@ -63,6 +63,8 @@ Canvas::render(Renderer& renderer, Filter filter)
 
   Painter& painter = renderer.get_painter();
 
+  //auto viewport_backup = m_context.get_viewport();
```
Comment (tobbi) [inline src/video/canvas.cpp:66]: What is this needed for?

**Review by tobbi — CHANGES_REQUESTED** [review]

File: src/control/joystick_manager.hpp (hunk 2 above)
Comment (Semphriss) [reply src/control/joystick_manager.hpp:57]: `src/supertux/menu/multiplayer_player_menu` needs read-write access to the mapping (to avoid having multiple players bound to the same joystick)

File: src/object/player.cpp (hunk 3 above)
Comment (Semphriss) [reply src/object/player.cpp:141]: It's a static member function

File: src/supertux/game_session.cpp (hunk 4 above)
Comment (Semphriss) [reply src/supertux/game_session.cpp:102]: The number of users is dynamic; someone can plug their controller mid-game and someone else can unplug theirs. I'll try to investigate further.

File: src/supertux/menu/cheat_apply_menu.cpp (hunk 5 above)
Comment (Semphriss) [reply src/supertux/menu/cheat_apply_menu.cpp:37]: Yea, it was the second thing I had to fix but I was too lazy to implement it now :smile:

File: src/supertux/sector.cpp (hunk 11 above)
Comment (Semphriss) [reply src/supertux/sector.cpp:417]: An attempt at making a split-screen camera. I left it there for future maintainers, so they have a working example, in case I happen to get bus-factored. I can remove it if preferred.

File: src/supertux/sector.cpp (hunk 12 above)
Comment (Semphriss) [reply src/supertux/sector.cpp:797]: The iterator used here (`it`) is our own implementation of an iterator-*like* object; it lacks many functions like `get()` or others. I can try to see if it works here.

Also, IMO `std::transform` is harder to understand here, since there's no actual "transform"; is there some copy-only equivalent?

File: src/trigger/climbable.cpp (hunk 13 above)
Comment (Semphriss) [reply src/trigger/climbable.cpp:139]: We don't yet, indeed

File: src/video/canvas.cpp (hunk 14 above)
Comment (Semphriss) [reply src/video/canvas.cpp:66]: Leftovers of experimentations, will remove

File: src/supertux/game_session.cpp (hunk 4 above)
Comment (Semphriss) [reply src/supertux/game_session.cpp:102]: It can be reproduced: Play the game with 2 players, remove a player, press escape and restart the level: a crash will occur.

File: src/control/keyboard_config.cpp [hunk 15]
```diff
@@ -16,38 +16,56 @@
 
 #include "control/keyboard_config.hpp"
 
+#include <regex>
```
Comment (tobbi) [inline src/control/keyboard_config.cpp:19]: What do you need the include for?

File: src/object/endsequence.hpp [hunk 16]
```diff
@@ -30,24 +32,28 @@ class EndSequence : public GameObject
...
   void stop(); /**< stop playing EndSequence, mark it as done playing */
-  bool is_tux_stopped() const; /**< returns true if Tux has reached his final position */
+  bool is_running() const; /**< returns true if the ending cinematic started */
+  bool is_tux_stopped(int player); /**< returns true if Tux has reached his final position */
   bool is_done() const; /**< returns true if EndSequence has finished playing */
   virtual bool is_saveable() const override {
     return false;
   }
 
+  const Controller* get_controller(int player);
```
Comment (tobbi) [inline src/object/endsequence.hpp:44]: Can this be marked `const` ?

File: src/supertux/menu/cheat_apply_menu.cpp [hunk 17]
```diff
@@ -0,0 +1,91 @@
...
+
+CheatApplyMenu::CheatApplyMenu(std::function<void(Player&, int)> callback) :
+  m_callback_1(nullptr),
+  m_callback_2(callback),
+  m_stack_count(1)
+{
+  add_label(_("Apply cheat to player"));
+  add_hl();
+
+  add_intfield("Count", &m_stack_count, -2);
```
Comment (tobbi) [inline src/supertux/menu/cheat_apply_menu.cpp:55]: This needs translation tags iirc

File: src/supertux/menu/keyboard_menu.cpp [hunk 18]
```diff
@@ -109,37 +127,39 @@ KeyboardMenu::refresh()
...
-  micf = dynamic_cast<ItemControlField*>(&get_item_by_id(static_cast<int>(Control::PEEK_DOWN)));
-  if (micf) micf->change_input(get_key_name(kbd_cfg.reversemap_key(Control::PEEK_DOWN)));
+  if (micf) micf->change_input(get_key_name(kbd_cfg.reversemap_key(m_player_id, Control::ACTION)));
 
-  if (g_config->developer_mode) {
-    micf = dynamic_cast<ItemControlField*>(&get_item_by_id(static_cast<int>(Control::CHEAT_MENU)));
-    if (micf) micf->change_input(get_key_name(kbd_cfg.reversemap_key(Control::CHEAT_MENU)));
+  if (m_player_id == 0)
+  {
+    micf = dynamic_cast<ItemControlField*>(&get_item_by_id(static_cast<int>(Control::PEEK_LEFT)));
```
Comment (tobbi) [inline src/supertux/menu/keyboard_menu.cpp:144]: Somehow, I'd love for this to be an array of the different controls and then iterating over that.

**Review by tobbi — COMMENTED** [review]
Do you remember the infinite monkey theorem? I think we need that, but for code review.
Nice job with everything, but I'm not really mentally present to review this to the extent that's required here. I'm just like *code, code, code* while rethinking my life choices. And then I ask myself WWJD (what would Jesus do?)...and then I'm like *screw it*...by the way: Could Jesus be considered a cro(i)ssant? Because cross...ha ha ha...yeah got it, you don't joke about that. Sorry if I hurt your religious feelings...Or should that be re-lychee-ous? 

Anyway, I'm outta here, let's have someone else review the code, just to be sure.

File: src/control/keyboard_config.cpp (hunk 15 above)
Comment (Semphriss) [reply src/control/keyboard_config.cpp:19]: Code experimentation artifact. I should get myself some playground for this :laughing:

File: src/object/endsequence.hpp (hunk 16 above)
Comment (Semphriss) [reply src/object/endsequence.hpp:44]: It can't, because under the hood it uses the private `get_code_controller()`, which is non-const because it lazily creates the controller. This is useful because it avoids the ending sequence to query the status of all players in the game, but it has the downside of forcing the functions to be non-const.

File: src/supertux/menu/keyboard_menu.cpp (hunk 18 above)
Comment (Semphriss) [reply src/supertux/menu/keyboard_menu.cpp:144]: Not all controls are rebindable; `ESCAPE`, `MENU_SELECT` and `MENU_SELECT_SPACE` aren't.

**Comment by Riggs333** [comment]
I downloaded the appimage for Ubuntu 64 from this build:
https://github.com/SuperTux/supertux/actions/runs/1763023049#artifacts

My system:
Ubuntu 20.04.3
5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I plugged in 4 USB controllers (Retro SNES style) before starting the game.
When starting a level four players/penguins appear.
But only one player can be moved with a controller.
No button of the other controllers have an effect.
But with the keyboard at least 3 player can be controlled (via arrows, WASD and IJKL).

In the menu for multiplayer settings I see all detected players with the 4 different "USB gamepads" assigned.

"Auto-manage Players" is checked
"Allow Multibind" is unchecked.

Output of `usb-devices` for two of the controllers:
```
T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=123 Spd=1.5 MxCh= 0
D:  Ver= 1.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=081f ProdID=e401 Rev=01.06
S:  Product=USB gamepad
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

T:  Bus=01 Lev=01 Prnt=01 Port=01 Cnt=03 Dev#=124 Spd=1.5 MxCh= 0
D:  Ver= 1.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=081f ProdID=e401 Rev=01.06
S:  Product=USB gamepad           
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```

In the settings for the joysting controls (key binding) I can assign actions to buttons of other controllers.

How can I provide any more relevant information to debug this issue?

**Comment by Semphriss** [comment]
@Riggs333 Most likely issue: Go in Options -> Setup Joystick; did you check "Manual Configuration"? Try disabling this setting and trying again. If that fixes the issue, then I need to fix something there; I haven't tested extensively using manual configuration.

If that doesn't work:

Go in Options -> Multiplayer settings -> Manage Players -> [Any player], then check the list of controllers:

image

Make sure that:
1. All controllers are prefixed either with a `[number]` or an arrow (`->`)
2. All player IDs (in your case: 1, 2, 3 and 4) are assigned to a controller. Note that the player you choose when entering the menu will have its ID replaced by an arrow (`->`).

If all controllers are mapped to a player, and all players are mapped to a controller, then it might be that either SDL or your OS don't support your controller very well. Try running 0.6.3 with all your controllers; you should be able to control Tux with all 4 controllers at once. You can also test your controllers using SuperTuxKart.

Also:
- If all 4 players appear then it detected all 4 controllers successfully, and it mapped them automatically to 4 different players, as expected given your settings.
- Check your player config for every player in Options -> Multiplayer settings -> Manage Players. Every player should have exactly one controller prefixed with `->`, and no two players should have the same controller mapped to them (if your controllers are similarly named, the order should be preserved across menus).

**Comment by Riggs333** [comment]
Thanks for your quick reply, @Semphriss!

> @Riggs333 Most likely issue: Go in Options -> Setup Joystick; did you check "Manual Configuration"? Try disabling this setting and trying again. If that fixes the issue, then I need to fix something there; I haven't tested extensively using manual configuration.

Disabling "Manual Configuration" does **not** fix the issue.

> Make sure that:
> 
> 1. All controllers are prefixed either with a `[number]` or an arrow (`->`)
> 2. All player IDs (in your case: 1, 2, 3 and 4) are assigned to a controller. Note that the player you choose when entering the menu will have its ID replaced by an arrow (`->`).

I checked that and I can confirm this is the case as you described. All players are there and assigned an dedicated controlller:








 
> If all controllers are mapped to a player, and all players are mapped to a controller, then it might be that either SDL or your OS don't support your controller very well. Try running 0.6.3 with all your controllers; you should be able to control Tux with all 4 controllers at once. You can also test your controllers using SuperTuxKart.

I tested **0.6.3** with all 4 controllers connected but I am only able to control Tux with **one of them** (additionally to the keyboard).
**SuperTuxKart** works like a charm with all 4 controllers (split screen 4 players).

The following might be interesting:
I can control 3 of the 4 Tux players with the keyboard. Here is the automatic setup of the keyboard controls:



Player 2:


Player 3:


Player 4:


So it looks like the 4 players are assigned to keyboard controls.

For the **joystick setup** there is only one set of controls:

In the joystick setup I can also assign an action like jump for example to a button of any of the other controllers. In the game this button works than.

I hope this information helps.
Let me know if I can do any other tests or provide debug info.

**Comment by Semphriss** [comment]
My personal controllers work fine on my side; I'll need to investigate further. It might take a bit longer, though.

**Comment by Semphriss** [comment]
@Riggs333 Can you open a separate issue? Since the issue is also applicable on current master, the problem can most likely be fixed there directly.

**Comment by TriVoxel** [comment]
Hey here's a fun idea: instead of recoloring the main character, could be different species of penguins or even a small character editor to add cosmetics like a Fedora, Red Hat, striped socks, maybe even distribution logos to the chest. Just some ideas. I know that's a whole other beast of a feature list, but I think it'd be really cool. Maybe look at the multiplayer of Ultimate Chicken Horse for inspiration. You can add a scarf or change color and so on and it's basic but effective.

**Comment by Semphriss** [comment]
Characters are already planned. When they will be ready for use in-game is another question.

Quote from me, a few messages above:
> The colors are meant to be temporary; there has been some discussion with various people about making a bunch of playable characters, although there isn't any centralized place to hold all that yet.
