### PR TITLE
Fix sporadic crash on worldmap select

### LINKED ISSUE #2920: Game crashes sporadically when selecting a different world
**SuperTux version:**
Development state b77810534218881a1dfd8a8a5ca384188c17bcff

**System information:**
macOs Ventura 13.6.6

##### Expected behavior
No crash when selecting another world

##### Actual behavior
Game crashes sporadically with segfault

##### Steps to reproduce actual behavior
- Start game in story mode.
- Repeat following until crash: Press action button and select a different world.

##### Additional debugging information
                                                                                                                      
Stacktrace:                                                                                                                                         
```
1  std::vector<std::unique_ptr<GameObject, std::default_delete<GameObject>>>::begin() const vector                   1547 0x10099f2a0    
2  GameObjectRange<worldmap::Tux>::begin() const                                            game_object_iterator.hpp 118  0x10099f16c    
3  worldmap::Tux& GameObjectManager::get_singleton_by_type<worldmap::Tux>() const           game_object_manager.hpp  120  0x10099d051    
4  worldmap::Camera::get_camera_pos_for_tux() const                                         camera.cpp               85   0x100afcba9    
5  worldmap::Camera::update(float)                                                          camera.cpp               47   0x100afca8e    
6  worldmap::WorldMapSector::update(float)                                                  worldmap_sector.cpp      278  0x100b2a9f1    
7  worldmap::WorldMap::update(float)                                                        worldmap.cpp             148  0x100b1d3a1    
8  worldmap::WorldMapScreen::update(float, Controller const&)                               worldmap_screen.cpp      57   0x100b25cec    
9  ScreenManager::update_gamelogic(float)                                                   screen_manager.cpp       312  0x1009d4317    
10 ScreenManager::loop_iter()                                                               screen_manager.cpp       625  0x1009d568f    
11 ScreenManager::run()                                                                     screen_manager.cpp       665  0x1009d5bba    
12 Main::launch_game(CommandLineArguments const&)                                           main.cpp                 653  0x10083238c    
13 Main::run(int, char * *)                                                                 main.cpp                 739  0x10083405e    
14 main                                                                                     main.cpp                 30   0x1000077e3    
```
The stacktrace is a bit misleading, the problem seems to be that in ```WorldMapSector& get_sector() const { return *m_sector; }``` m_sector is nullptr. My assumption is, that on world change a new WorldMap is allocated which leads to an updated worldmap currenton. ```WorldMapSector::current()->get_sector()``` refers to the new WorldMap currenton which has no sector yet setup via ```set_sector``` and thus ```WorldMap::get_sector()``` tries to dereference a nullptr.

### PR DESCRIPTION
**Pull request by Brockengespenst**
Fixes nullptr dereferencing when a new WorldMap has been allocated, but no sector has been setup yet

Fixes #2920

### CODE REVIEW

File: src/worldmap/worldmap_sector.cpp [hunk 1]
```diff
@@ -62,14 +62,16 @@ WorldMapSector::current()
...
-  m_camera(new Camera),
+  m_camera(nullptr),
   m_tux(&add<Tux>(&parent)),
   m_spawnpoints(),
   m_initial_fade_tilemap(),
   m_fade_direction()
 {
   BIND_WORLDMAP_SECTOR(*this);
 
+  m_camera.reset(new Camera(*this));
```
Comment (tobbi) [inline src/worldmap/worldmap_sector.cpp:73]: Can the `new Camera(*this)` part be moved to the initilization list or would that lead to things being uninitializaed?

Comment (Brockengespenst) [reply src/worldmap/worldmap_sector.cpp]: Works indeed, I thought it might make problems, because the object is not fully constructed, yet. But clang seems to be fine with that, and so am I.

File: src/worldmap/camera.cpp [hunk 2]
```diff
@@ -31,7 +31,8 @@ const float CAMERA_PAN_TIME_MAX = 0.52213f;
 
 namespace worldmap {
 
-Camera::Camera() :
+Camera::Camera(WorldMapSector& world_map_sector) :
+  m_world_map_sector(world_map_sector),
```
Comment (Vankata453) [inline src/worldmap/camera.cpp:35]: `worldmap` shouldn't be separated, since it's used as one word.

Comment (Brockengespenst) [reply src/worldmap/camera.cpp]: I changed it. I was unsure because of the capitalization in the class name.

**Review by tobbi — APPROVED** [review]

**Review by Vankata453 — APPROVED** [review]
