### PR TITLE
Fixed problem with narrow levels

### LINKED ISSUE #1270: Graphics glitch for narrow levels
**SuperTux version:** 0.6.0 beta 2
**System information:** GNU/Linux

##### Expected behavior
If you play a narrow level (a level that has a low overall width), the left and right level bounds are black or rendered in some other way that indicates that its out of level bounds.

##### Actual behavior
There's a weird graphical glitch at the left and right level bounds.

Evidence: Level “Flower Bonus” from Bonus Island III:

https://satoshiupload.com/images/1TScduq6Zw.png

##### Steps to reproduce actual behavior
Play with a wide screen resolution a level with a low level width.
I recommend playing a couple of levels in Bonus Island III, which has a couple of narrow levels where this can be seen.

Affected Bonus Island III levels:

* The Toilette Zone
* Flower Bonus
* Deep, deeper …
* … the deepest
* (possibly other levels)

### PR DESCRIPTION
**Pull request by Zwatotem**
Levels narrower than display used to be displayed on whole screen. 
Now The part out of level limits is a black stripe.
Fixes #1270

### CODE REVIEW

**Comment by busybody42** [comment]
No!
Let's just zoom in instead!
Zoom in so that the part out of bounds isn't visible, because the camera zooms in so we CAN'T see it!

File: src/object/vertical_stripes.cpp [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+{
+}
+
+VerticalStripes::~VerticalStripes()
+{
+}
+
+void
+VerticalStripes::update(float dt_sec)
+{
```
Comment (tobbi) [inline src/object/vertical_stripes.cpp]: ::update() gets run once every frame. I'm wondering whether this should be placed somewhere more appropriate.
