### PR TITLE
Fixed buffer overflow on game termination

### LINKED ISSUE #671: buffer overflow when game is terminated
compiled with -O0 -g3 -fsanitize=address

when just starting and terminating the game right after, there is a heap buffer overflow reported
````
=================================================================
==29014==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000d7e88 at pc 0x0000007df94c bp 0x7fff20e19640 sp 0x7fff20e19630
READ of size 8 at 0x6020000d7e88 thread T0
    #0 0x7df94b in std::unique_ptr<Screen, std::default_delete<Screen> >::get() const /usr/include/c++/6.2.1/bits/unique_ptr.h:305
    #1 0x7dbd11 in ScreenManager::handle_screen_switch() /home/matthias/vcs/github/supertux/src/supertux/screen_manager.cpp:356
    #2 0x7dcbbf in ScreenManager::run(DrawingContext&) /home/matthias/vcs/github/supertux/src/supertux/screen_manager.cpp:427
    #3 0x7ae3d3 in Main::launch_game() /home/matthias/vcs/github/supertux/src/supertux/main.cpp:448
    #4 0x7af727 in Main::run(int, char**) /home/matthias/vcs/github/supertux/src/supertux/main.cpp:504
    #5 0x7aa1b9 in main /home/matthias/vcs/github/supertux/src/main.cpp:23
    #6 0x7fda9c821400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #7 0x7aa0c9 in _start (/home/matthias/vcs/github/supertux/build/supertux2+0x7aa0c9)

0x6020000d7e88 is located 8 bytes to the left of 8-byte region [0x6020000d7e90,0x6020000d7e98)
allocated by thread T0 here:
    #0 0x7fda9fa47e90 in operator new(unsigned long) (/lib64/libasan.so.3+0xc7e90)
    #1 0x7e6018 in __gnu_cxx::new_allocator<std::unique_ptr<Screen, std::default_delete<Screen> > >::allocate(unsigned long, void const*) (/home/matthias/vcs/github/supertux/build/supertux2+0x7e6018)
    #2 0x7e5cc4 in std::allocator_traits<std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > > >::allocate(std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > >&, unsigned long) /usr/include/c++/6.2.1/bits/alloc_traits.h:416
    #3 0x7e5884 in std::_Vector_base<std::unique_ptr<Screen, std::default_delete<Screen> >, std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > > >::_M_allocate(unsigned long) (/home/matthias/vcs/github/supertux/build/supertux2+0x7e5884)
    #4 0x7e421a in void std::vector<std::unique_ptr<Screen, std::default_delete<Screen> >, std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > > >::_M_emplace_back_aux<std::unique_ptr<Screen, std::default_delete<Screen> > >(std::unique_ptr<Screen, std::default_delete<Screen> >&&) (/home/matthias/vcs/github/supertux/build/supertux2+0x7e421a)
    #5 0x7e2b44 in void std::vector<std::unique_ptr<Screen, std::default_delete<Screen> >, std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > > >::emplace_back<std::unique_ptr<Screen, std::default_delete<Screen> > >(std::unique_ptr<Screen, std::default_delete<Screen> >&&) /usr/include/c++/6.2.1/bits/vector.tcc:101
    #6 0x7e07c0 in std::vector<std::unique_ptr<Screen, std::default_delete<Screen> >, std::allocator<std::unique_ptr<Screen, std::default_delete<Screen> > > >::push_back(std::unique_ptr<Screen, std::default_delete<Screen> >&&) /usr/include/c++/6.2.1/bits/stl_vector.h:933
    #7 0x7dbc5e in ScreenManager::handle_screen_switch() /home/matthias/vcs/github/supertux/src/supertux/screen_manager.cpp:346
    #8 0x7dc3be in ScreenManager::run(DrawingContext&) /home/matthias/vcs/github/supertux/src/supertux/screen_manager.cpp:379
    #9 0x7ae3d3 in Main::launch_game() /home/matthias/vcs/github/supertux/src/supertux/main.cpp:448
    #10 0x7af727 in Main::run(int, char**) /home/matthias/vcs/github/supertux/src/supertux/main.cpp:504
    #11 0x7aa1b9 in main /home/matthias/vcs/github/supertux/src/main.cpp:23
    #12 0x7fda9c821400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/6.2.1/bits/unique_ptr.h:305 in std::unique_ptr<Screen, std::default_delete<Screen> >::get() const
Shadow bytes around the buggy address:
  0x0c0480012f80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa fd fa
  0x0c0480012f90: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c0480012fa0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c0480012fb0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c0480012fc0: fa fa fd fd fa fa 00 fa fa fa fd fd fa fa fd fa
=>0x0c0480012fd0: fa[fa]00 fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c0480012fe0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c0480012ff0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 fa
  0x0c0480013000: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c0480013010: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x0c0480013020: fa fa 00 fa fa fa 00 fa fa fa 00 fa fa fa 00 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==29014==ABORTING
````

@ d19abb9952c593f05ad9c3f5a4a5c3652639bc70

### PR DESCRIPTION
**Pull request by InsightGit**
This pull request fixes a buffer overflow that occurred on game termination, as reported by Issue #671. This overflow was caused from the QUIT_ACTION clearing the entirety of the m_screen_stack stack. However, the code that dealt with the last screen in that screen stack was still being executed after that QUIT_ACTION code was executed, causing a buffer overflow from trying to get the back of an empty vector.

Closes #671

### CODE REVIEW

**Comment by InsightGit** [comment]
I was unable to reproduce the buffer overflow upon aborting a level I had seen a couple days ago, so I am marking this PR as no longer WIP and awaiting approval.

File: src/supertux/screen_manager.cpp [hunk 1]
```diff
@@ -330,7 +330,8 @@ ScreenManager::handle_screen_switch()
 
       // move actions to a new vector since setup() might modify it
       auto actions = std::move(m_actions);
-
+      bool quitactiontriggered = false;
```
Comment (christ2go) [inline src/supertux/screen_manager.cpp]: Can you use a variable name which is better to read? (Maybe camel-case or use _).

File: src/supertux/screen_manager.cpp [hunk 2]
```diff
@@ -353,21 +354,25 @@ ScreenManager::handle_screen_switch()
...
-          current_screen->leave();
-        }
-
-        if (!m_screen_stack.empty())
+        if (current_screen != m_screen_stack.back().get())
         {
-          m_screen_stack.back()->setup();
-          m_speed = 1.0;
-          m_waiting_threads.wakeup();
+          if(current_screen != nullptr) {
```
Comment (christ2go) [inline src/supertux/screen_manager.cpp]: Please use `if (`

**Comment by tobbi** [comment]
Thanks 🎉
