### PR TITLE
Wind: Add `current` subtype and fix particle orientation

### LINKED ISSUE #2592: Improving the `Wind` object
While functional, wind could be giving a couple tweaks to make it more robust.

If you make wind too strong you get push with no way of fighting against it. Make it too low and you won't get blown at all and only get slowed down when walking against it. At lower speeds wind should actually push Tux slightly when standing

It feels to me that wind, instead of pushing Tux, it gives him a set amount of speed in a specific direction, resulting in it feeling very unnatural!

https://github.com/SuperTux/supertux/assets/20615048/fadd5c72-e612-419f-96c2-8c3fda26a459

https://github.com/SuperTux/supertux/assets/20615048/e19b3a8e-c0de-456b-8890-bec8a5ea30c9

---

Also, another idea I had regarding wind:

An underwater object type for the wind object, `Current`, that instead of wind particles uses bubbles.
It will function nearly identical to wind, however I assume it may require some slight adjustments for the underwater setting.

Some of these things maybe be:
- Dive Mine is unaffected by it (this allows for fun dodging underwater)
- You have better control within the current for better navigation and correcting

### PR DESCRIPTION
**Pull request by Hypernoot**
Partially resolves #2592 but does only the graphical part. The physics is unchanged.

### CODE REVIEW

File: src/object/sprite_particle.hpp [hunk 1]
```diff
@@ -32,11 +32,11 @@ class SpriteParticle final : public GameObject
   SpriteParticle(SpritePtr sprite, const std::string& action,
                  const Vector& position, AnchorPoint anchor,
                  const Vector& velocity, const Vector& acceleration,
-                 int drawing_layer = LAYER_OBJECTS-1, bool notimeout = false, Color color = Color::WHITE);
+                 int drawing_layer = LAYER_OBJECTS-1, bool notimeout = false, Color color = Color::WHITE, float angle = 0);
```
Comment (bruhmoent) [inline src/object/sprite_particle.hpp]: `LAYER_OBJECTS-1` -> `LAYER_OBJECTS - 1`

File: src/object/sprite_particle.hpp [hunk 2]
```diff
@@ -32,11 +32,11 @@ class SpriteParticle final : public GameObject
...
   SpriteParticle(const std::string& sprite_name, const std::string& action,
                  const Vector& position, AnchorPoint anchor,
                  const Vector& velocity, const Vector& acceleration,
-                 int drawing_layer = LAYER_OBJECTS-1, bool notimeout = false, Color color = Color::WHITE);
+                 int drawing_layer = LAYER_OBJECTS-1, bool notimeout = false, Color color = Color::WHITE, float angle = 0);
```
Comment (bruhmoent) [inline src/object/sprite_particle.hpp]: Same here

File: src/object/wind.cpp [hunk 3]
```diff
@@ -96,6 +97,14 @@ Wind::get_settings()
   return result;
 }
 
+GameObjectTypes
+Wind::get_types() const {
```
Comment (bruhmoent) [inline src/object/wind.cpp]: Ensure that `{` always start on a `\n`

File: src/object/wind.cpp [hunk 4]
```diff
@@ -107,19 +116,26 @@ Wind::update(float dt_sec_)
...
   if (graphicsRandom.randf(0.f, 100.f) < (m_col.m_bbox.get_width() / 32.f) * (m_col.m_bbox.get_height() / 32.f))
   {
     // Emit a particle
-	  if (fancy_wind)
+    if (fancy_wind)
     {
-	    Sector::get().add<SpriteParticle>("images/particles/wind.sprite", (std::abs(speed.x) > std::abs(speed.y)) ? "default" : "flip", ppos, ANCHOR_MIDDLE, pspeed, Vector(0, 0), m_layer); 
-	  }
-	  else
+      const float angle = std::atan2(speed.y, speed.x) * float(180/M_PI);
```
Comment (bruhmoent) [inline src/object/wind.cpp]: `const float angle = std::atan2(speed.y, speed.x) * static_cast<float>(180.0 / M_PI);`

**Review by bruhmoent — CHANGES_REQUESTED** [review]

**Comment by Frostwithasideofsalt** [comment]
remind me to test this again later

File: src/object/wind.cpp (hunk 4 above)
Comment (Hypernoot) [reply src/object/wind.cpp]:
```
src/object/wind.cpp:126:76: style: Floating-point cast causes loss of precision. [suspiciousFloatingPointCast]
      const float angle = std::atan2(speed.y, speed.x) * static_cast<float>(180.0 / M_PI);
```

**Comment by tobbi** [comment]
> remind me to test this again later

You wanted to be reminded, @Frostwithasideofsalt

**Review by bruhmoent — APPROVED** [review]
