### PR TITLE
Prioritize players in `GameObject` list

### LINKED ISSUE #2679: Throwing an Iceblock while mid-air or running kills Tux
**SuperTux version:** The latest Nightly Build
**System information:** Windows 11 22H2

##### Expected behavior
Tux should not die when throwing an Iceblock while either running or in mid-air.
##### Actual behavior
Tux dies when throwing an Iceblock under any of these conditions.
##### Steps to reproduce actual behavior
Throw an Iceblock while running or in mid-air. This was tested in Via Nostalgica.

### PR DESCRIPTION
**Pull request by Vankata453**
Players are now prioritized in a `GameObjectManager`'s `GameObject` list, allowing for them to be updated first for input processing.

Fixes #2679.

### CODE REVIEW

**Comment by MrIceblock** [comment]
Oh my gawdingf Finally

**Comment by MatusGuy** [comment]
GYATTTT

**Review by MatusGuy — APPROVED** [review]

**Comment by tylerandari13** [comment]
Cant wait for these comments to get deleted

Seriously tho this is PEAK

File: src/object/player.hpp [hunk 1]
```diff
@@ -79,6 +79,7 @@ class Player final : public MovingObject,
   virtual void on_flip(float height) override;
   virtual bool is_saveable() const override { return false; }
   virtual bool is_singleton() const override { return false; }
+  virtual bool priority_in_list() const override { return true; }
```
Comment (tobbi) [inline src/object/player.hpp:82]: Doesn't say what kind of list. That shit is nondescript as fuck.

**Review by tobbi — COMMENTED** [review]
I have no fucking clue how that fixes the issue.

**Comment by tulpenkiste** [comment]
Tested, it works 🔥

**Comment by MatusGuy** [comment]
@tobbi to be honest go with the flow

File: src/object/player.hpp (hunk 1 above)
Comment (MatusGuy) [reply src/object/player.hpp:82]: may i recommend `has_object_manager_priority`

Comment (tobbi) [reply src/object/player.hpp:82]: You may. I'll allow it

**Review by Rusty-Box — APPROVED** [review]

**Comment by mrkubax10** [comment]
> I have no fucking clue how that fixes the issue.

Moves player out of collision before it's handled by other objects (so for example player won't be hurt by Mr Iceblock).

**Comment by tobbi** [comment]
Can you add a virtual method for index and then sort the shit?

**Comment by MatusGuy** [comment]
tobbi what if two objects have the same index

**Comment by tobbi** [comment]
We don't care about the rest of the objects, just the player who can get -INT_MAX.

**Comment by MatusGuy** [comment]
Then why would you make the priority function return an index if you're not gonna use it anywhere else?

**Comment by Frostwithasideofsalt** [comment]
I'm gonna try to review this so this can finally get merged

**Review by MatusGuy — APPROVED** [review]

**Review by tobbi — APPROVED** [review]

**Comment by Frostwithasideofsalt** [comment]
YYYYYYYYYYEEEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHH

**Comment by tulpenkiste** [comment]
les goooo
