### PR TITLE
Fix levelset / worldmap creation

### LINKED ISSUE #503: Editor: Editing worldmap should be possible from level select's level subset properties
Currently, you can only edit the worldmap if a level was loaded previously. This doesn't make sense. You should be able to edit a worldmap even from the Level subset properties.

### PR DESCRIPTION
**Pull request by tobbi**
This fixes #503 among other things, and removes some performance inefficiencies in the code, for example we don't need to load a savegame when we just want to display the levels.

### CODE REVIEW

**Comment by tobbi** [comment]
Please test thoroughly everyone!

File: src/supertux/menu/contrib_menu.cpp [hunk 1]
```diff
@@ -84,7 +84,8 @@ ContribMenu::ContribMenu() :
   {
     try
     {
-      auto levelset = std::unique_ptr<Levelset>(new Levelset(*it));
+      auto levelset =
+        std::unique_ptr<Levelset>(new Levelset(*it, /* recursively = */ true));
```
Comment (christ2go) [inline src/supertux/menu/contrib_menu.cpp]: Shoudl the `/* recursively = */`be here?

Comment (tobbi) [inline src/supertux/menu/contrib_menu.cpp]: Yes, that's to indicate what the extra parameter means.
